
const REDUCE_LOADED_FLOORS_FETCH_KEY = '__baiBaiToolkitReduceLoadedFloorsFetchPatched';
const REDUCE_LOADED_FLOORS_LIMIT = 10;
const REDUCE_LOADED_FLOORS_INPUT_IDS = new Set(['chat_truncation', 'chat_truncation_counter']);
const REDUCE_LOADED_FLOORS_CHAT_PATHS = new Set(['/api/chats/get', '/api/chats/group/get']);
const FAST_CHAT_SEARCH_FETCH_KEY = '__baiBaiToolkitFastChatSearchFetchPatched';
const BAIBAOKU_FAST_SEARCH_URL = '/api/plugins/baibaoku/v1/chats/fast-search';
const FAST_CHAT_BACKUPS_FETCH_KEY = '__baiBaiToolkitFastChatBackupsFetchPatched';
const NATIVE_CHAT_BACKUPS_LIST_URL = '/api/backups/chat/get';
const BAIBAOKU_FAST_CHAT_BACKUPS_LIST_URL = '/api/plugins/baibaoku/v1/chat-backups/fast-list';
const FAST_CHAT_LIST_SCROLL_STYLE_ID = 'bai_bai_toolkit_fast_chat_list_scroll_style';
const CHAT_BACKUP_LIST_SELECTOR = '.chatBackupsList';
const CHAT_BACKUP_ITEM_SELECTOR = '.chatBackupsListItem';
const CHAT_BACKUP_ITEM_INTRINSIC_SIZE_VAR = '--bai-bai-toolkit-chat-backup-item-height';
const CHAT_BACKUP_ITEM_INTRINSIC_FALLBACK_PX = 64;
const LONG_CHAT_DOM_RENDER_STYLE_ID = 'bai_bai_toolkit_long_chat_dom_render_style';
const MESSAGE_EDIT_BOTTOM_ACTIONS_STYLE_ID = 'bai_bai_toolkit_message_edit_bottom_actions_style';
const CHAT_DELETE_EDIT_HANDLER_KEY = '__baiBaiToolkitChatDeleteEditHandler';
const CHAT_DELETE_MESSAGE_DELETED_HANDLER_KEY = '__baiBaiToolkitChatDeleteMessageDeletedHandler';
const CHAT_DELETE_GENERATION_ACTION_HANDLER_KEY = '__baiBaiToolkitChatDeleteGenerationActionHandler';
const MESSAGE_EDIT_BOTTOM_ACTIONS_STATE_KEY = '__baiBaiToolkitMessageEditBottomActions';
const WELCOME_RECENT_CHAT_DIRECT_OPEN_HANDLER_KEY = '__baiBaiToolkitWelcomeRecentChatDirectOpenHandler';
const WELCOME_RECENT_CHAT_DIRECT_OPEN_CURRENT_HANDLER_KEY = '__baiBaiToolkitWelcomeRecentChatDirectOpenCurrentHandler';
const MESSAGE_COMPLETION_SCROLL_HANDLER_KEY = '__baiBaiToolkitMessageCompletionScrollHandler';
const MOBILE_AUTO_KEYBOARD_HANDLER_KEY = '__baiBaiToolkitMobileAutoKeyboardHandler';
const MOBILE_AUTO_KEYBOARD_FOCUS_PATCH_KEY = '__baiBaiToolkitMobileAutoKeyboardFocusPatched';
const MOBILE_AUTO_KEYBOARD_JQUERY_FOCUS_PATCH_KEY = '__baiBaiToolkitMobileAutoKeyboardJQueryFocusPatched';
const MOBILE_AUTO_KEYBOARD_JQUERY_TRIGGER_PATCH_KEY = '__baiBaiToolkitMobileAutoKeyboardJQueryTriggerPatched';
const MOBILE_MESSAGE_EDIT_SCROLL_TOP_PATCH_KEY = '__baiBaiToolkitMessageEditScrollTopPatched';
const LONG_CHAT_DOM_RENDER_TEXT_THRESHOLD = 60000;
const LONG_CHAT_DOM_RENDER_SINGLE_MESSAGE_THRESHOLD = 12000;
const LONG_CHAT_DOM_RENDER_MIN_TEXT_THRESHOLD = 24000;
const LONG_CHAT_DOM_RENDER_MESSAGE_COUNT_THRESHOLD = 20;
const LONG_CHAT_DOM_RENDER_SCROLL_BOTTOM_SETTLE_MS = 900;
const LONG_CHAT_DOM_RENDER_SCROLL_BOTTOM_STABLE_FRAMES = 6;
const LONG_CHAT_DOM_RENDER_SCROLL_BOTTOM_TOLERANCE = 8;
const LONG_CHAT_DOM_RENDER_UNCONTAINED_TAIL_MESSAGES = 4;
const LONG_CHAT_DOM_RENDER_GENERATION_ANCHOR_RELEASE_MS = 1200;
const LONG_CHAT_DOM_RENDER_LATEST_MESSAGE_TOP_OFFSET_RATIO = 0.18;
const LONG_CHAT_DOM_RENDER_LATEST_MESSAGE_TOP_OFFSET_MIN = 24;
const LONG_CHAT_DOM_RENDER_LATEST_MESSAGE_TOP_OFFSET_MAX = 160;
const LONG_CHAT_DOM_RENDER_WIDTH_BUCKET_SIZE = 80;
const LONG_CHAT_DOM_RENDER_DEBUG_LOG_INTERVAL_MS = 500;
const LONG_CHAT_DOM_RENDER_DEBUG_LOG_SLOW_MS = 16;
const LONG_CHAT_DOM_RENDER_ESTIMATE_SAFETY_MULTIPLIER = 1.25;
const LONG_CHAT_DOM_RENDER_ESTIMATE_EXTRA_PX = 80;
const LONG_CHAT_DOM_RENDER_ESTIMATE_MAX_HEIGHT = 80000;
const LONG_CHAT_DOM_RENDER_ESTIMATOR_ALPHA = 0.35;
const LONG_CHAT_DOM_RENDER_ESTIMATOR_MAX_SCALE = 4;
const LONG_CHAT_DOM_RENDER_FORCE_DISABLED = true; // iOS fork: content-visibility 在 WebKit 有白屏/崩溃 bug，永久禁用
const LONG_CHAT_DOM_RENDER_BOTTOM_ANCHOR_CLASS = 'bai-bai-toolkit-long-chat-bottom-anchor';
const LONG_CHAT_DOM_RENDER_BOTTOM_ANCHORED_CLASS = 'bai-bai-toolkit-long-chat-bottom-anchored';
const LONG_CHAT_DOM_RENDER_HEIGHT_VAR = '--bai-bai-toolkit-long-chat-mes-height';
const CHAT_DELETE_EDIT_WINDOW_MS = 5000;
const MOBILE_AUTO_KEYBOARD_DIRECT_FOCUS_WINDOW_MS = 1500;
const MOBILE_MESSAGE_EDIT_SCROLL_RESTORE_TOLERANCE = 2;
const MOBILE_MESSAGE_EDIT_SCROLL_RESTORE_DELAYS = [0, 50, 160];
const MESSAGE_EDIT_BOTTOM_ACTION_SCROLL_RESTORE_DELAYS = [0, 50, 160, 360, 800];
const MOBILE_MESSAGE_EDIT_CARET_VISIBLE_PADDING = 24;
const MOBILE_MESSAGE_EDIT_CARET_CONTEXT_LINES = 2;
const MOBILE_MESSAGE_EDIT_EDITOR_SCROLL_INTENT_MS = 1200;
const CHAT_GENERATION_ACTION_SELECTOR = '#send_but, #option_regenerate, #option_continue, #option_impersonate, #mes_continue, #mes_impersonate';
const CHAT_MESSAGE_EDIT_SELECTOR = '#chat .mes_edit';
const WELCOME_PANEL_SELECTOR = '#chat .welcomePanel';
const WELCOME_RECENT_CHAT_SELECTOR = '#chat .welcomePanel .recentChat';
const WELCOME_RECENT_CHAT_ACTION_SELECTOR = '.renameChat, .deleteChat, .pinChat, button, a, input, select, textarea';
const MESSAGE_EDIT_BOTTOM_ACTIONS_CLASS = 'bai-bai-toolkit-message-edit-bottom-actions';
const MESSAGE_EDIT_BOTTOM_ACTIONS_RELEVANT_SELECTOR = `#curEditTextarea, .mes_edit_buttons, .mes_edit_done, .mes_edit_cancel, .${MESSAGE_EDIT_BOTTOM_ACTIONS_CLASS}`;
const MESSAGE_EDIT_BOTTOM_ACTIONS_CONTROL_SCOPE_SELECTOR = `.mes_edit_buttons, .mes_edit_done, .mes_edit_cancel, .${MESSAGE_EDIT_BOTTOM_ACTIONS_CLASS}`;
const MOBILE_MESSAGE_EDIT_SELECTOR = '#curEditTextarea, .reasoning_edit_textarea';
const MOBILE_AUTO_KEYBOARD_TARGET_SELECTOR = '#curEditTextarea, #select_chat_search';
const MOBILE_CHAT_ENTRY_KEYBOARD_TARGET_SELECTOR = '#send_textarea';
const MOBILE_DIRECT_KEYBOARD_TARGET_SELECTOR = `${MOBILE_AUTO_KEYBOARD_TARGET_SELECTOR}, ${MOBILE_CHAT_ENTRY_KEYBOARD_TARGET_SELECTOR}`;
const CHAT_MANAGEMENT_POPUP_SELECTOR = '#shadow_select_chat_popup';
const CHAT_MANAGEMENT_LIST_SELECTOR = '#select_chat_div';
const MESSAGE_COMPLETION_SOUND_SOURCES = new Set(['builtin', 'url', 'local']);
const MESSAGE_COMPLETION_SOUND_DB_NAME = 'baiBaiToolkit';
const MESSAGE_COMPLETION_SOUND_DB_VERSION = 1;
const MESSAGE_COMPLETION_SOUND_STORE = 'messageCompletionSounds';
const MESSAGE_COMPLETION_SOUND_LOCAL_KEY = 'local';
const MESSAGE_COMPLETION_SOUND_MAX_LOCAL_BYTES = 5 * 1024 * 1024;
const MESSAGE_COMPLETION_SOUND_COOLDOWN_MS = 1000;
const MESSAGE_COMPLETION_SOUND_KEEP_ALIVE_SRC = 'data:audio/wav;base64,UklGRigAAABXQVZFZm10IBAAAAABAAEAESsAACJWAAACABAAZGF0YQQAAAAAAA==';
const BUILTIN_COMPLETION_SOUNDS = [
    { id: 'guoke-bell', label: '果壳铃', file: '果壳铃.mp3' },
    { id: 'stardew-fish', label: '星露谷 - 钓鱼上钩', file: '星露谷-钓鱼上钩.mp3' },
    { id: 'stardew-achievement', label: '星露谷 - 成就', file: '星露谷-成就.mp3' },
    { id: 'pokemon-heal', label: '宝可梦 - 治疗', file: '宝可梦-治疗.mp3' },
    { id: 'pokemon-berry', label: '宝可梦 - 摘果子', file: '宝可梦-摘果子.mp3' },
    { id: 'zelda-get', label: '塞尔达 - 获取', file: '塞尔达-获取.mp3' },
    { id: 'zelda-complete', label: '塞尔达 - 完成', file: '塞尔达-完成.mp3' },
    { id: 'bubble', label: 'Q弹气泡', file: 'Q弹气泡.mp3' },
    { id: 'line-yangqin', label: 'LINE - 扬琴', file: 'LINE-扬琴.mp3' },
];

export {
    BAIBAOKU_FAST_CHAT_BACKUPS_LIST_URL,
    BAIBAOKU_FAST_SEARCH_URL,
    BUILTIN_COMPLETION_SOUNDS,
    CHAT_BACKUP_ITEM_INTRINSIC_FALLBACK_PX,
    CHAT_BACKUP_ITEM_INTRINSIC_SIZE_VAR,
    CHAT_BACKUP_ITEM_SELECTOR,
    CHAT_BACKUP_LIST_SELECTOR,
    CHAT_DELETE_EDIT_HANDLER_KEY,
    CHAT_DELETE_EDIT_WINDOW_MS,
    CHAT_DELETE_GENERATION_ACTION_HANDLER_KEY,
    CHAT_DELETE_MESSAGE_DELETED_HANDLER_KEY,
    CHAT_GENERATION_ACTION_SELECTOR,
    CHAT_MANAGEMENT_LIST_SELECTOR,
    CHAT_MANAGEMENT_POPUP_SELECTOR,
    CHAT_MESSAGE_EDIT_SELECTOR,
    FAST_CHAT_BACKUPS_FETCH_KEY,
    FAST_CHAT_LIST_SCROLL_STYLE_ID,
    FAST_CHAT_SEARCH_FETCH_KEY,
    LONG_CHAT_DOM_RENDER_BOTTOM_ANCHORED_CLASS,
    LONG_CHAT_DOM_RENDER_BOTTOM_ANCHOR_CLASS,
    LONG_CHAT_DOM_RENDER_DEBUG_LOG_INTERVAL_MS,
    LONG_CHAT_DOM_RENDER_DEBUG_LOG_SLOW_MS,
    LONG_CHAT_DOM_RENDER_ESTIMATE_EXTRA_PX,
    LONG_CHAT_DOM_RENDER_ESTIMATE_MAX_HEIGHT,
    LONG_CHAT_DOM_RENDER_ESTIMATE_SAFETY_MULTIPLIER,
    LONG_CHAT_DOM_RENDER_ESTIMATOR_ALPHA,
    LONG_CHAT_DOM_RENDER_ESTIMATOR_MAX_SCALE,
    LONG_CHAT_DOM_RENDER_FORCE_DISABLED,
    LONG_CHAT_DOM_RENDER_GENERATION_ANCHOR_RELEASE_MS,
    LONG_CHAT_DOM_RENDER_HEIGHT_VAR,
    LONG_CHAT_DOM_RENDER_LATEST_MESSAGE_TOP_OFFSET_MAX,
    LONG_CHAT_DOM_RENDER_LATEST_MESSAGE_TOP_OFFSET_MIN,
    LONG_CHAT_DOM_RENDER_LATEST_MESSAGE_TOP_OFFSET_RATIO,
    LONG_CHAT_DOM_RENDER_MESSAGE_COUNT_THRESHOLD,
    LONG_CHAT_DOM_RENDER_MIN_TEXT_THRESHOLD,
    LONG_CHAT_DOM_RENDER_SCROLL_BOTTOM_SETTLE_MS,
    LONG_CHAT_DOM_RENDER_SCROLL_BOTTOM_STABLE_FRAMES,
    LONG_CHAT_DOM_RENDER_SCROLL_BOTTOM_TOLERANCE,
    LONG_CHAT_DOM_RENDER_SINGLE_MESSAGE_THRESHOLD,
    LONG_CHAT_DOM_RENDER_STYLE_ID,
    LONG_CHAT_DOM_RENDER_TEXT_THRESHOLD,
    LONG_CHAT_DOM_RENDER_UNCONTAINED_TAIL_MESSAGES,
    LONG_CHAT_DOM_RENDER_WIDTH_BUCKET_SIZE,
    MESSAGE_COMPLETION_SCROLL_HANDLER_KEY,
    MESSAGE_COMPLETION_SOUND_COOLDOWN_MS,
    MESSAGE_COMPLETION_SOUND_DB_NAME,
    MESSAGE_COMPLETION_SOUND_DB_VERSION,
    MESSAGE_COMPLETION_SOUND_KEEP_ALIVE_SRC,
    MESSAGE_COMPLETION_SOUND_LOCAL_KEY,
    MESSAGE_COMPLETION_SOUND_MAX_LOCAL_BYTES,
    MESSAGE_COMPLETION_SOUND_SOURCES,
    MESSAGE_COMPLETION_SOUND_STORE,
    MESSAGE_EDIT_BOTTOM_ACTIONS_CLASS,
    MESSAGE_EDIT_BOTTOM_ACTIONS_CONTROL_SCOPE_SELECTOR,
    MESSAGE_EDIT_BOTTOM_ACTIONS_RELEVANT_SELECTOR,
    MESSAGE_EDIT_BOTTOM_ACTIONS_STATE_KEY,
    MESSAGE_EDIT_BOTTOM_ACTIONS_STYLE_ID,
    MESSAGE_EDIT_BOTTOM_ACTION_SCROLL_RESTORE_DELAYS,
    MOBILE_AUTO_KEYBOARD_DIRECT_FOCUS_WINDOW_MS,
    MOBILE_AUTO_KEYBOARD_FOCUS_PATCH_KEY,
    MOBILE_AUTO_KEYBOARD_HANDLER_KEY,
    MOBILE_AUTO_KEYBOARD_JQUERY_FOCUS_PATCH_KEY,
    MOBILE_AUTO_KEYBOARD_JQUERY_TRIGGER_PATCH_KEY,
    MOBILE_AUTO_KEYBOARD_TARGET_SELECTOR,
    MOBILE_CHAT_ENTRY_KEYBOARD_TARGET_SELECTOR,
    MOBILE_DIRECT_KEYBOARD_TARGET_SELECTOR,
    MOBILE_MESSAGE_EDIT_CARET_CONTEXT_LINES,
    MOBILE_MESSAGE_EDIT_CARET_VISIBLE_PADDING,
    MOBILE_MESSAGE_EDIT_EDITOR_SCROLL_INTENT_MS,
    MOBILE_MESSAGE_EDIT_SCROLL_RESTORE_DELAYS,
    MOBILE_MESSAGE_EDIT_SCROLL_RESTORE_TOLERANCE,
    MOBILE_MESSAGE_EDIT_SCROLL_TOP_PATCH_KEY,
    MOBILE_MESSAGE_EDIT_SELECTOR,
    NATIVE_CHAT_BACKUPS_LIST_URL,
    REDUCE_LOADED_FLOORS_CHAT_PATHS,
    REDUCE_LOADED_FLOORS_FETCH_KEY,
    REDUCE_LOADED_FLOORS_INPUT_IDS,
    REDUCE_LOADED_FLOORS_LIMIT,
    WELCOME_PANEL_SELECTOR,
    WELCOME_RECENT_CHAT_ACTION_SELECTOR,
    WELCOME_RECENT_CHAT_DIRECT_OPEN_CURRENT_HANDLER_KEY,
    WELCOME_RECENT_CHAT_DIRECT_OPEN_HANDLER_KEY,
    WELCOME_RECENT_CHAT_SELECTOR,
};
